name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/repo/aws-three-tier-webapplication

            git pull

            docker stop flask-container || true
            docker rm flask-container || true

            docker build -t flask-app .

            docker run -d \
              -p 8080:8080 \
              --name flask-container \
              flask-app
